### ISSUE TITLE
TSK#25 - CREAR HomeController("/")

### ISSUE THREAD

**Issue by erkcgn** [webapp-service/webappservice#39]
- [x] GET ("/") -> Devolvera retornar el index.html -> Vista Usuarios sin registro

	-Cargarle la lista de ProviderDTO (Provider-Attendance-Score)
	-Cargarle la lista de todos los Attendance

- [x] GET ("/user/id") -> Debera retornar el user_index.html -> Vista Usuarios registrados

	 -Cargarle la lista de ProviderDTO (Provider-Attendance-Score)
	-Cargarle la lista de todos los Attendance

- [x] GET ("/providers/id") -> Debera retornar el providers_index.html -> Vista Providers registrados

	-Cargarle la lista de ProviderDTO (Provider-Attendance-Score)
	-Cargarle la lista de todos los Attendance

**Comment by ArturoFreites** [comment]
Query para cargar el objeto ProviderDTO

**Comment by LucaRamponi** [comment]
@ArturoFreites Terminada la primer subtarea de la task.
Esperamos las vistas user.index y provider.index

**Comment by MartinGiovaruzzo** [comment]
@ArturoFreites Terminadas las dos tareas faltantes
* Usuarios registrados
* Proveedores registrados
