### ISSUE TITLE
TSK#29 - CREAR UserController("/user")

### ISSUE THREAD

**Issue by erkcgn** [webapp-service/webappservice#43]
- [x] GET("/id/contract") -> Debera retornar user_menu.html que mostrará el menu del user con todos los servicios contratados

			-Cargarle todos los contratos del user 

- [x] POST("/User/Register") -> Debera retornar user_menu.html que mostrará el menu del user con todos los servicios contratados
                        -Cargar registro del User le html del form user_form.html

**Comment by ArturoFreites** [comment]
El back devuelve el User completo
